export const books = [
  {
    id: 1,
    title: "Making India Awesome",
    author: "Chetan Bhagat ",
    price: 30,
    number_of_sheets: 200,
    category: "Fiction",
  },
  {
    id: 2,
    title: "One Indian Girl",
    author: "Chetan Bhagat",
    price: 20,
    number_of_sheets: 150,
    category: "Tech",
  },
  {
    id: 3,
    title: "Naked Triangle",
    author: "Balwant Gargi",
    price: 30,
    number_of_sheets: 250,
    category: "Fiction",
  },
  {
    id: 4,
    title: "A Brush with Life ",
    author: "Satish Gujral",
    price: 18,
    number_of_sheets: 180,
    category: "Manga",
  },
  {
    id: 5,
    title: "A House for Mr. Biswas ",
    author: "V.S. Naipaul",
    price: 22,
    number_of_sheets: 220,
    category: "Tech",
  },
  {
    id: 6,
    title: "Ain-i-Akbari ",
    author: "Abul Fazl",
    price: 48,
    number_of_sheets: 280,
    category: "Tech",
  },
  {
    id: 7,
    title: "Akbarnama",
    author: "Abul Fazl",
    price: 26,
    number_of_sheets: 190,
    category: "Romance",
  },
  {
    id: 8,
    title: "Arthashastra ",
    author: "Kautilya",
    price: 44,
    number_of_sheets: 170,
    category: "Philosophy",
  },
  {
    id: 9,
    title: "An Autobiography",
    author: "Jawaharlal Nehru",
    price: 30,
    number_of_sheets: 210,
    category: "Manga",
  },
];
